version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # No Dependabot updates for .nuspec projects available yet.
  # See: https://github.com/dependabot/dependabot-core/issues/1182
