name: Packaging check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up NuGet.exe
      uses: NuGet/setup-nuget@v1.2.0
    
    - name: Package .nuspec file
      run: nuget pack Xyaneon.Games.nuspec
    
    # TODO: Publish to nuget.org only on valid pushes to main
